export const data = [
  {
    id: 1,
    title: "Leboncoin",
    date: "Mai 2020",
    languages: ["React", "Express.js", "MongoDB", "Stripe"],
    infos: "Réplique de l'application web Leboncoin, avec paiement",
    img: "./assets/images/projet-1.png",
    link: "https://leboncoin-dianebodin.netlify.app",
  },
  {
    id: 2,
    title: "Formnest",
    date: "Juin 2020",
    languages: ["React", "Express.js", "MongoDB"],
    infos: "Création de formulaire et visualisation des réponses",
    img: "./assets/images/projet-2.png",
    link: "https://formnest-dianebodin.netlify.app",
  },
  {
    id: 3,
    title: "Shopping",
    date: "Août 2020",
    languages: ["React", "Redux", "Context API", "Bootstrap"],
    infos: "Application web e-commerce",
    img: "./assets/images/projet-3.png",
    link: "https://shopping-dianebodin.netlify.app",
  },
  {
    id: 4,
    title: "Shopping 2",
    date: "Mai 2021",
    languages: ["React", "Commerce.js", "Stripe", "Material-UI"],
    infos: "Application web e-commerce, avec paiement",
    img: "./assets/images/projet-4.png",
    link: "https://shopping-ii-dianebodin.netlify.app",
  },
];